// email.action
export const EMAIL_REQ_ERROR = 'EMAIL_REQ_ERROR';
export const EMAIL_REQ_DATA = 'EMAIL_REQ_DATA';
export const EMAIL_RECV_DATA = 'EMAIL_RECV_DATA';
export const EMAIL_CACHE_DATA = 'EMAIL_CACHE_DATA';

//account.action
export const ACCOUNT_CHECKING = 'ACCOUNT_CHECKING';
export const ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
export const ACCOUNT_ENABLED = 'ACCOUNT_ENABLED';
export const ACCOUNT_EXPIRED = 'ACCOUNT_EXPIRED';
