[target.x86_64-linux-android]
image = "x86_64-linux-android:v2"
# pre-build = ["apt-get update && apt-get install --assume-yes libsqlite3-dev:$CROSS_DEB_ARCH"]

[target.aarch64-linux-android]
image = "aarch64-linux-android:v1"

[target.armv7-linux-androideabi]
image = "armv7-linux-androideabi:v1"

[target.i686-linux-android]
image = "i686-linux-android:v1"