# log4rs.yaml
# 检查配置文件变动的时间间隔
refresh_rate: 300 seconds

# appender 负责将日志收集到控制台或文件，可配置多个
appenders:
  # 可以自定义命名
  console:
    kind: console
    encoder:
      pattern: '{h({d(%Y-%m-%d %H:%M:%S)})}-{P}::{l}::{M}::{m}{n}'
  rolling_file:
    kind: rolling_file
    path: 'log/rust-log.log'
    encoder:
      #log 信息格式
      pattern: '{d}<{l}> {M}::{L} :{m}{n}'
    policy:
      trigger:
        kind: size
        #限制文件大小
        limit: 1mb
      #新建文件并保存所有日志文件
      roller:
        kind: fixed_window
        base: 0
        count: 10
        pattern: 'log/rust-log-{}.log'

# 对全局log进行配置
root:
  level: debug
  appenders:
    - rolling_file
    - console
